Arrays homework
Despods/AQA_MTS pull request #2
Opened 2023-12-04 18:33 UTC by Despods

2023-12-11 13:48 UTC, wildpioneer requested changes

2023-12-11 13:48 UTC, wildpioneer commented on TypesAndOperators/task1.cs
> +
Форматирование - не оставляй ненужные пустые строки

2023-12-11 13:48 UTC, wildpioneer commented on TypesAndOperators/task2.cs
> +        foreach (int i in array1)//выводим изначальный массив в консоль
Форматирование:  Перед for, foreach, if, switch и методами нужна пустая строка

2023-12-11 13:48 UTC, wildpioneer commented on TypesAndOperators/task2.cs
> +                    array2[tmp] = array1[i];
инкриментацию можно делать сразу в момент использования

2023-12-11 13:48 UTC, wildpioneer commented on TypesAndOperators/task4.cs
> +        static void insertArray(int[] arrays) //метод для заполнения массива рандом значениями
Описание методов лучше всего выносить в конец - чтобы не мешали читать основной код

2023-12-11 14:19 UTC, Despods commented on TypesAndOperators/task2.cs
> +                    array2[tmp] = array1[i];
Не совсем понимаю как это сделать
Инкрементация - это увеличение переменной на единицу
Как отлично от моего варианта еще можно сделать

2024-01-29 09:56 UTC, wildpioneer commented
Проверено

2024-01-29 09:56 UTC, closed without merging